Net/ThemeName "MMD-Dark"
Net/IconThemeName "HighContrastInverse"
Gtk/FontName "Lato 11"
Gtk/ApplicationPreferDarkTheme 1
Net/EnableEventSounds 0
Net/EnableInputFeedbackSounds 0
Xft/Antialias 1
Xft/Hinting 1
Xft/HintStyle "hintslight"
Xft/RGBA "none"
